"""
Author: Olly Bayley
Created: 08/11/2023

The aim of this package is to take the analysis settings from the analysis_setup.json,
the calibrated campaign data from the LAMSPrescreen (as a .pkl) and the most recent DAD
Chromatogram, process the latest data and then generate a report.

Notes:
1) There may still be some discrepancies in some variable naming with some referred to as 'hplc'
and some referred to as 'lcms'. In all cases, the variables refer to the same type of DAD
chromatogram data that can be generated by either technique.

2) This class inherits methods and variables from the LAMSBase and is therefore subject to the
file naming restrictions discussed in the LAMSBase class.
"""
# --- Imports ---
import os
import time
import logging
import json
import script_utilities as util
from LAMA.LCMSLama.lams_base import LamsBase
from LAMA.LCMSLama.user_interaction.campaign import HplcDadCampaign
from LAMA.LCMSLama.user_interaction.user_objects import DadInput
from LAMA.LCMSLama.report.main import report_single_run, full_report


class LamsAnalysis(LamsBase):
    """
    LAMS Class which controls the run-by-run analysis
    """

    def __init__(self, path_to_experiment, path_to_analysis_setup_json=None, path_to_data=None):
        super().__init__(path_to_experiment, path_to_analysis_setup_json, path_to_data)

        self.experiment_campaign_single = HplcDadCampaign()
        self.experiment_campaign_full = HplcDadCampaign()
        self.run_result_dict = None
        self.most_recent_sample = None
        self.analyse_run_count = 0
        self.setup_logging()

        self.calib_pkl_filename = "campaign_calibration.pkl"
        self.exp_json_filename = "experimental_setup.json"

        self.reaction_conc = 0.2  # Temp Default Value

    def setup_logging(self):
        """
        Sets up the logging paths for the utility script
        """
        path = os.path.join(self.path_to_experiment, self.report_folder_name)
        name = "LAMS_Analysis"
        util.configure_log_reports(path=path, script_name=name)

    @util.time_method
    def prepare_analysis(self):
        """
        Readies the analysis object for the run-by-run analysis/reporting.
        """
        try:
            self.load_setup_data()
            self.load_lcms_data()
            self.init_bkg_obj()
            self.init_istd_obj()
            self.set_analysis_settings()
            self.load_lams_prescreen_calibration()

        except RuntimeError as error:
            print(
                "LAMS Analysis failed to initialise properly. See the log for further details"
            )
            util.handle_error(f"LAMSAnalysis failed to initialise properly:{error}")

    def run_analysis(self):
        """
        Controls the run order of the run-by-run analysis
        """
        try:
            start_time = time.time()

            self.load_lcms_data()
            self.get_reaction_conc()
            self.add_most_recent_data_to_campaign()
            print(self.experiment_campaign_single.hplc_inputs)
            self.process_most_recent_run()
            self.report_latest_run()
            self.reset_single_run_camp()

            end_time = time.time()
            logging.info("###### Run analysis complete after %s seconds. ######",
                         round(end_time - start_time, 3)
                         )
            print(
                f"Run analysis complete after {round(end_time - start_time, 3)} seconds."
            )
            self.analyse_run_count = self.analyse_run_count + 1

        except RuntimeError as error:
            util.handle_error(f"LAMSAnalysis failed to analyse the run:{error}")
            print(
                "LAMSAnalysis failed to analyse the run. See the log for further details"
            )

    @util.time_method
    def get_reaction_conc(self):
        """
        Gets the reaction concentration from the experiment.json
        """
        try:
            with open(
                    os.path.join(self.path_to_experiment, self.exp_json_filename),
                    mode='r',
                    encoding='utf-8'
            ) as infile:
                exp_setup_data = json.load(infile)
                identifier_unit_dict = exp_setup_data.get('identifier_unit_dict', {})

                conc = None
                for compound_info in identifier_unit_dict.values():
                    unit = compound_info.get('unit', '').lower()
                    if unit in ['mm', 'um']:
                        conc = compound_info.get('proportion')
                        break  # Break the loop if a match is found
                self.reaction_conc = conc

        except FileNotFoundError as error:
            util.handle_error(f"File not found: {error}", error)
        except PermissionError as error:
            util.handle_error(f"Permission error: {error}", error)
        except json.JSONDecodeError as error:
            util.handle_error(f"JSON decode error: {error}", error)

    @util.time_method
    def load_lams_prescreen_calibration(self):
        """
        Loads the processed campaign data generated by the LAMSPrescreen.
        """
        try:
            calib_pkl_path = os.path.join(
                self.path_to_experiment,
                self.report_folder_name,
                self.calib_pkl_filename,
            )
            self.experiment_campaign_single.load_campaign(calib_pkl_path)
            self.experiment_campaign_full.load_campaign(calib_pkl_path)

        except OSError as error:
            util.handle_error(
                f"Failed to load the campaign_calibration.pkl due to OSError: {error}"
            )
        except Exception as error:
            util.handle_error(f"Failed to load the campaign_calibration.pkl: {error}")

    @util.time_method
    def reset_single_run_camp(self):
        """
        Reloads the LAMSPrescreen calibration data
        """
        try:
            self.experiment_campaign_single = HplcDadCampaign()
            calib_pkl_path = os.path.join(
                self.path_to_experiment,
                self.report_folder_name,
                self.calib_pkl_filename,
            )
            self.experiment_campaign_single.load_campaign(calib_pkl_path)

        except Exception as error:
            util.handle_error(f"Failed to load the campaign_calibration.pkl: {error}")

    @util.time_method
    def add_most_recent_data_to_campaign(self):
        """
        Gets the most recent data file and adds it to the campaign. The lcms_exp_run_data
        is sorted by run number when it is loaded, allowing us to get the most recent run
        by taking the last entry in the list (index of -1). filename must finish with run number
        """
        try:
            sample_list = [
                exp_run
                for exp_run in self.lcms_exp_run_data
                if self.reaction_sample_tag in exp_run.lower()
            ]
            if len(sample_list) == 0:
                util.handle_error("No samples found in the loaded run data")
            self.most_recent_sample = sample_list[-1]
            dad_input = DadInput(
                self.most_recent_sample,
                gradient=self.gradient_bkg,
                istd=self.internal_standard_added,
            )
            self.experiment_campaign_single.add_hplc_input(dad_input)
            self.experiment_campaign_full.add_hplc_input(dad_input)

        except Exception as error:
            util.handle_error(
                f"An exception occurred when adding the most recent run to the campaign: {error}"
            )

    @util.time_method
    def process_most_recent_run(self):
        """
        Simple process call to both long and short campaigns
        """
        try:
            self.experiment_campaign_single.process_new_hplc_input()
            self.experiment_campaign_full.process_new_hplc_input()
        except Exception as error:
            util.handle_error(f"An exception occurred during processing: {error}")

    @util.time_method
    def report_latest_run(self):
        """
        Writes the yield, conversion and relative peak are of idetified compounds to a results.json
        """
        try:
            report_path = os.path.join(self.path_to_experiment, self.report_folder_name)
            if not os.path.exists(report_path):
                os.makedirs(report_path)

            self.run_result_dict = report_single_run(
                self.experiment_campaign_single, report_path, self.most_recent_sample
            )

            run = self.most_recent_sample
            conv = round(self.calculate_conv(), 1)
            react_yield = round(self.calculate_yield(), 1)
            selectivity = round((react_yield/conv)*100, 1)

            output = {"Run": run, "Conversion": conv, "Yield": react_yield, "Selectivity": selectivity}
            for compound, measured_int in self.run_result_dict.items():
                output[f"{compound} integral"] = round(measured_int["integral"], 4)

            with open(os.path.join(report_path, "results.json"), "w", encoding="utf-8") as outfile:
                json.dump(output, outfile, indent=4)

        except FileNotFoundError as error:
            util.handle_error(f"File not found: {error}", error)
        except PermissionError as error:
            util.handle_error(f"Permission error: {error}", error)
        except json.JSONDecodeError as error:
            util.handle_error(f"JSON decode error: {error}", error)
        except Exception as error:
            util.handle_error(
                f"An exception occurred when reporting the run data: {error}", error
            )

    @util.time_method
    def report_all_runs(self):
        """
        Generates the final report of all the data in the full campaign
        """
        try:
            report_path = os.path.join(self.path_to_experiment, self.report_folder_name)
            full_report(self.experiment_campaign_full, report_path)

        except OSError as error:
            util.handle_error(
                f"An exception occurred when reporting the run data due to a path issue: {error}"
            )
        except Exception as error:
            util.handle_error(f"An exception occurred when reporting the run data: {error}")

    @util.time_method
    def save_full_campaign(self):
        """
        Saves the full campaign data as a .pkl
        """
        try:
            self.experiment_campaign_full.save_campaign(
                os.path.join(
                    self.path_to_experiment,
                    self.report_folder_name,
                    "full_campaign.pkl",
                ),
                remove_raw_data=False,
            )

        except Exception as error:
            util.handle_error(f"An error occurred when saving the campaign: {error}")

    def calculate_conv(self):
        """
        Calculates the conversion if the reaction conc is given and the SM is found.
        """
        try:
            starting_mat_name = None
            remaining_starting_mat_conc = 0
            # find the name of the calibrated starting material
            for value in self.input_compounds_info.values():
                if value["Role"] == "Starting Material":
                    starting_mat_name = value["Compound"]

            if starting_mat_name in self.run_result_dict:
                remaining_starting_mat_conc = self.run_result_dict[starting_mat_name][
                    "concentration"
                ]
            # basic conversion calculation
            conversion = (1 - (remaining_starting_mat_conc / self.reaction_conc)) * 100
            return conversion

        except ValueError as error:
            util.handle_error(
                f"A ValueError occurred when calculating the conversion: {error}"
            )
            return None
        except TypeError as error:
            util.handle_error(
                f"A TypeError occurred when calculating the conversion: {error}"
            )
            return None
        except (IndexError, KeyError) as error:
            util.handle_error(
                f"A out-of-bounds error occurred when calculating the conversion: {error}"
            )
            return None
        except Exception as error:
            util.handle_error(
                f"An exception occurred when calculating the conversion: {error}"
            )
            return None

    def calculate_yield(self):
        """
        Calculates the yield if the reaction conc is given and the product is found.
        """
        try:
            product_name = None
            measured_product_conc = 0
            # find the name of the calibrated starting material
            for value in self.input_compounds_info.values():
                if value["Role"] == "Product":
                    product_name = value["Compound"]
            if product_name in self.run_result_dict:
                measured_product_conc = self.run_result_dict[product_name][
                    "concentration"
                ]
            # basic yield calculation
            reaction_yield = (measured_product_conc / self.reaction_conc) * 100
            return reaction_yield

        except ValueError as error:
            util.handle_error(f"A ValueError occurred when calculating the yield: {error}")
            return None
        except TypeError as error:
            util.handle_error(f"A TypeError occurred when calculating the yield: {error}")
            return None
        except (IndexError, KeyError) as error:
            util.handle_error(
                f"A out-of-bounds error occurred when calculating the yield: {error}"
            )
            return None
        except Exception as error:
            util.handle_error(f"An exception occurred when calculating the yield: {error}")
            return None


if __name__ == "__main__":
    repo_path = os.path.normpath(os.path.join(__file__, "..", "..", ".."))
    path_to_exp = os.path.join(
        repo_path, "Tests", "Test_data", "LCMSLama_test_data_dir"
    )
    path_to_anal_json = path_to_exp
    analysis_obj = LamsAnalysis(path_to_exp, path_to_anal_json)
    analysis_obj.analysis_json_filename = "test_analysis_setup.json"
    analysis_obj.dad_data_folder_name = "standard_test_data"
    analysis_obj.prepare_analysis()
    analysis_obj.run_analysis()
