"""
Author: Olly Bayley
Created: 08/11/2023

The aim of this package is to take calibration settings from the analysis_setup.json and DAD
Chromatogram data collectd on an HPLC/UPLC/LC-MS and generate a processed campaign object
containing all the calibration data for the campaign. This campaign object can then be used as
a reference for all subsequent analysis.

Notes:
1) The script assumes that if the compound needs to be calibrated, the generated LCMS/HPLC files
will include the 'compound name' in the 'file name'. This file naming also applies to the internal
standard but *NOT* the background. The background file should be set to "gradient" by default but
 can be changed with the "self.gradient_bkg_file_tag" The compound names used in the file name
 should be in lowercase and have underscores ("_") instead of spaces (" ").

2) There may still be some discrepancies in some variable naming with some referred to as 'hplc'
and some referred to as 'lcms'. In all cases, the variables refer to the same type of DAD
chromatogram data that can be generated by either technique.

3) This class inherits methods and variables from the LAMSBase and is therefore subject to the
file naming restrictions discussed in the LAMSBase class.
"""
# --- Imports ---
import os
import script_utilities as util
from LAMA.LCMSLama.lams_base import LamsBase
from LAMA.LCMSLama.user_interaction.campaign import HplcDadCampaign
from LAMA.LCMSLama.user_interaction.user_objects import Compound, DadInput


class LamsPrescreen(LamsBase):
    """
    LAMS Class which controls the experiment calibration.
    """
    def __init__(self, path_to_experiment, path_to_analysis_setup_json=None, path_to_data=None):
        super().__init__(path_to_experiment, path_to_analysis_setup_json, path_to_data)

        self.calibration_pkl_filename = "campaign_calibration.pkl"

        self.experiment_campaign = HplcDadCampaign()  # Initialize a new campaign object

        # Valid compound roles only needed if listing compounds by role type.
        # See 'create_comp_calib_role_based_dicts'
        self.valid_calib_comp_roles = [
            "Starting Material",
            "Product",
            "Reagent",
            "Side Product",
            "Other",
        ]

        # Configure logging
        path = os.path.join(self.path_to_experiment, self.report_folder_name)
        name = "LAMS_Prescreen"
        util.configure_log_reports(path=path, script_name=name)

    def run_calibration(self):
        """
        Controls the run order of the prescreening
        """
        try:
            self.load_setup_data()
            print("setup info loaded")
            self.load_lcms_data()
            print("data loaded")
            self.init_bkg_obj()
            print("bkg created")
            if self.chromatogram_analysis_parameters.get("internal_standard_name"):
                self.init_istd_obj()
                self.add_istd_data_to_capaign()
                print("istd done")
            self.add_all_calib_comps_to_campaign()
            print("compounds added")
            self.set_analysis_settings()
            self.process_calibration_campaign()
            print("campaign processed")
            self.save_calibration_campaign()

            print("\nCampaign calibration successful. Now ready for analysis")

        except RuntimeError as error:
            print(
                "An error occurred during the campaign calibration. See the log for further details"
            )
            util.handle_error(f"LAMSPrescreen failed to initialise properly:{error}")

    @util.time_method
    def add_istd_data_to_capaign(self):
        """
        Adds the 'DadInput' object for the internal standard to the experiment campaign.
        * This method should only be called if an istd is specified in the analysis.json *
        """
        try:
            if self.lcms_exp_run_data is None:
                raise ValueError("No data has been loaded.")

            # istd data filename must match the internal standard name in the analysis.json
            istd_name = self.chromatogram_analysis_parameters.get(
                "internal_standard_name"
            )
            istd_file_tag = istd_name.replace(" ", "_").lower()

            run_data = self.lcms_exp_run_data
            # List comprehension gives a list of comps with the role_identifier in the name
            calibration_data = [exp_run for exp_run in run_data if istd_file_tag in exp_run.lower()]

            # Check that an istd_file has been added
            if len(calibration_data) == 0:
                raise ValueError("No istd run data has been found.")

            # loop added to catch if the standard has been run multiple times.
            for exp_run in calibration_data:
                istd_comp = Compound(istd_name, is_istd=True)
                compound_input = DadInput(exp_run, self.gradient_bkg, istd_comp)
                self.experiment_campaign.add_hplc_input(compound_input)
                print(f"istd: {istd_name} added to campaign")

        except (KeyError, AttributeError, ValueError, TypeError, IndexError) as error:
            util.handle_error(
                f"Incorrect paramter prevented the istd data being added to the campaign: {error}"
            )
        except Exception as error:
            util.handle_error(f"Failed to add istd data to the campaign: {error}")

    @util.time_method
    def create_comp_calibration_dict(self) -> dict:
        """
        Reads through the prescreen_info and returns a dictionary of the added compound names
        and concentrations where the *compound NAME* is used as the key.
        """
        try:
            comp_calibration_dict = {}
            if self.input_compounds_info is None:
                raise ValueError("No input compounds info has been loaded")

            for compound_info_dict in self.input_compounds_info.values():
                calibration_required = compound_info_dict.get(
                    "Calibration Required", ""
                )

                if "Yes" in calibration_required and compound_info_dict.get("Compound"):
                    comp_calibration_dict.update(
                        {
                            compound_info_dict.get("Compound"): list(
                                compound_info_dict.get("Calibration Concs", {}).values()
                            )
                        }
                    )
            return comp_calibration_dict

        except (ValueError, KeyError, IndexError) as error:
            util.handle_error(
                f"Failed to create a compound calibration dictionary due a lack of data: {error}"
            )
            return {}
        except Exception as error:
            util.handle_error(
                f"Failed to create a compound calibration dictionary: {error}"
            )
            return {}

    @util.time_method
    def add_comp_data_to_campaign(self, compound_name, given_concs=None):
        """
        Adds the corresponding 'DadInput' object to the experiment campaign for the compound it
        was passed. Multiple compound concs means multiple data files for the same compound,
        requiring multiple input objects.
        """
        try:
            # Catch if setup variables or data are not present
            if self.chromatogram_analysis_parameters is None:
                raise ValueError("Chromatogram analysis parameters are not set.")
            if self.lcms_exp_run_data is None:
                raise ValueError("No data has been loaded.")

            # Skip the re-loading of the internal standard
            if compound_name == self.chromatogram_analysis_parameters.get(
                "internal_standard_name"
            ):
                return

            if given_concs is None:
                given_concs = []

            role_file_tag = compound_name.replace(" ", "_").lower()

            calibration_data = [
                exp_run
                for exp_run in self.lcms_exp_run_data
                if role_file_tag in exp_run.lower()
            ]

            # Loop based on existing files prevents the system attempting to add files that don't
            # exist and allows for files to be added if the concentration wasn't given.
            # The concentrations must be given in the same order as they were run.
            for i, exp_run in enumerate(calibration_data):
                if i < len(given_concs):
                    compound = Compound(compound_name, given_concs[i])
                    compound_input = DadInput(
                        exp_run,
                        self.gradient_bkg,
                        compound=compound,
                        istd=self.internal_standard_added,
                    )
                else:
                    compound = Compound(compound_name)
                    compound_input = DadInput(
                        exp_run,
                        self.gradient_bkg,
                        compound=compound,
                        istd=self.internal_standard_added,
                    )
                self.experiment_campaign.add_hplc_input(compound_input)

        except (ValueError, KeyError, IndexError) as error:
            util.handle_error(
                f"Failed to add a compound to the campaign due a lack of data: {error}"
            )
        except Exception as error:
            util.handle_error(f"Failed to add a compound to the campaign: {error}")

    @util.time_method
    def add_all_calib_comps_to_campaign(self):
        """
        Calls a method to get a dict of compounds to calibrate, and then iterates through this dict
        to add the data for each of these compounds to the campaign object using a second method
        """
        try:
            calib_comp_dict = self.create_comp_calibration_dict()

            if not calib_comp_dict:
                raise ValueError("No compound data found for calibration")

            for comp_name, com_concs_list in calib_comp_dict.items():
                self.add_comp_data_to_campaign(
                    compound_name=comp_name, given_concs=com_concs_list
                )

        except (ValueError, KeyError, IndexError) as error:
            util.handle_error(
                f"Failed to add ALL compounds to the campaign due a lack of data: {error}"
            )
        except Exception as error:
            util.handle_error(f"Failed to add ALL compounds to the campaign: {error}")

    @util.time_method
    def process_calibration_campaign(self):
        """
        Processes the calibration data contained in the campaign object
        """
        try:
            self.experiment_campaign.process_all_hplc_input(self.analysis_settings)

        except Exception as error:
            util.handle_error(f"An error occurred when processing the campaign: {error}")

    @util.time_method
    def save_calibration_campaign(self):
        """
        Saves the processed camapign data as a .pkl
        """
        try:
            self.experiment_campaign.save_campaign(
                os.path.join(
                    self.path_to_experiment,
                    self.report_folder_name,
                    self.calibration_pkl_filename,
                ),
                remove_raw_data=False,
            )

        except Exception as error:
            util.handle_error(f"An error occurred when saving the campaign: {error}")


if __name__ == "__main__":
    repo_path = os.path.normpath(os.path.join(__file__, "..", "..", ".."))
    path_to_exp = os.path.join(
        repo_path, "Tests", "Test_data", "LCMSLama_test_data_dir"
    )
    path_to_anal_json = path_to_exp
    prescreen_obj = LamsPrescreen(path_to_exp, path_to_anal_json)
    prescreen_obj.analysis_json_filename = "test_analysis_setup.json"
    prescreen_obj.dad_data_folder_name = "standard_test_data"
    prescreen_obj.run_calibration()
